services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TomasNorre\Crawler\:
        resource: '../Classes/*'

    TomasNorre\Crawler\Command\BuildQueueCommand:
        tags:
            - name: 'console.command'
              command: 'crawler:buildQueue'

    TomasNorre\Crawler\Command\FlushQueueCommand:
        tags:
            - name: 'console.command'
              command: 'crawler:flushQueue'

    TomasNorre\Crawler\Command\ProcessQueueCommand:
        tags:
            - name: 'console.command'
              command: 'crawler:processQueue'
